development:
  servers: ["localhost:9160"]
  keyspace: "datastax_rails_development"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"DC1": "1"} 
  connection_options:
    timeout: 10
  solr:
    port: 8983
    path: /solr
    
test:
  servers: ["localhost:9160"]
  keyspace: "datastax_rails_test"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"DC1": "1"} 
  connection_options:
    timeout: 10
  solr:
    port: 8983
    path: /solr
        
